"""Extract MSL components for MLX metal_kernel dispatch.

Parses the full MSL source generated by our codegen (MSLCodeGen.emit())
and extracts the kernel body, header, and argument mappings needed by
mx.fast.metal_kernel().

MLX's metal_kernel auto-injects thread variables when they appear in the
SOURCE string (not header). We prepend local variable declarations to the
body to trigger injection and compute pid/lid from the injected variables.
"""

import re
from dataclasses import dataclass
from typing import List, Optional, Set


@dataclass
class MSLExtraction:
    """Components extracted from full MSL for metal_kernel dispatch."""

    kernel_name: str
    body: str               # Kernel body (between { })
    header: str             # Device functions, non-standard includes
    input_names: List[str]  # Read-only pointer arg names
    output_names: List[str] # Written-to pointer arg names
    scalar_names: List[str] # Non-pointer buffer arg names (xnumel, etc.)
    scalar_types: List[str] # MSL types for scalar args (int, float, etc.)
    output_ptr_indices: set = None  # Indices within ptr_args that are outputs
    uses_simd: bool = False
    uses_2d: bool = False
    uses_tpg: bool = False
    tpg_axes: Set[int] = None  # Which grid axes tpg is needed for (0, 1, 2)


def extract_msl_for_mlx(
    msl_source: str,
    output_arg_indices: Optional[List[int]] = None,
) -> MSLExtraction:
    """Parse full MSL into components for mx.fast.metal_kernel().

    Args:
        msl_source: Complete MSL source from emit_msl().
        output_arg_indices: Indices of pointer args that are stored-to.
            If None, all pointer args are treated as outputs (conservative).

    Returns:
        MSLExtraction with body, header, and arg mappings.
    """
    # Split into pre-kernel (includes, device functions) and kernel
    kernel_match = re.search(r'^kernel\s+void\s+(\w+)\s*\(', msl_source, re.MULTILINE)
    if not kernel_match:
        raise ValueError("No kernel function found in MSL source")

    kernel_name = kernel_match.group(1)
    pre_kernel = msl_source[:kernel_match.start()].strip()

    # Find kernel signature end (closing paren before opening brace)
    sig_start = kernel_match.start()
    brace_match = re.search(r'\)\s*\{', msl_source[sig_start:])
    if not brace_match:
        raise ValueError("Could not find kernel body opening brace")

    body_start = sig_start + brace_match.end()

    # Find matching closing brace (last `}` in source)
    body_end = msl_source.rstrip().rfind('}')
    if body_end < body_start:
        raise ValueError("Could not find kernel body closing brace")

    raw_body = msl_source[body_start:body_end]

    # Parse signature to extract args
    sig_text = msl_source[sig_start:sig_start + brace_match.start() + 1]
    ptr_args, scalar_args, thread_vars = _parse_signature(sig_text)

    # Classify pointer args as input vs output
    output_indices = set(output_arg_indices) if output_arg_indices else None
    input_names = []
    output_names = []
    output_ptr_idx_set = set()
    for i, (name, _dtype) in enumerate(ptr_args):
        if output_indices is None or i in output_indices:
            output_names.append(name)
            output_ptr_idx_set.add(i)
        else:
            input_names.append(name)

    scalar_names = [name for name, _ty in scalar_args]
    scalar_types = [ty for _name, ty in scalar_args]

    # Detect features
    uses_simd = 'sgitg' in thread_vars or 'tiisg' in thread_vars
    uses_2d = 'pid3' in sig_text or 'pid_y' in raw_body
    uses_tpg = 'tpg' in thread_vars or 'tpg3' in thread_vars

    # Detect which tpg axes are needed (from body references and signature)
    tpg_axes: Set[int] = set()
    if uses_tpg:
        tpg_axes.add(0)  # tpg (axis 0) always present when uses_tpg
    # Check for multi-axis tpg in the body (emitted as tpg_y, tpg_z)
    if re.search(r'\btpg_y\b', raw_body):
        tpg_axes.add(1)
        uses_tpg = True
    if re.search(r'\btpg_z\b', raw_body):
        tpg_axes.add(2)
        uses_tpg = True

    # Add synthetic scalar args for tpg dimensions.
    # These are injected by MLXLauncher at dispatch time.
    if uses_tpg:
        for axis in sorted(tpg_axes):
            tpg_scalar_name = f"__tpg_dim{axis}"
            scalar_names.append(tpg_scalar_name)
            scalar_types.append("uint")

    # Build header (device functions only — MLX provides metal_stdlib)
    header_parts = []
    for line in pre_kernel.split('\n'):
        line_s = line.strip()
        if line_s.startswith('#include') and 'metal_stdlib' not in line_s:
            header_parts.append(line_s)

    device_funcs = _extract_device_functions(pre_kernel)
    if device_funcs:
        header_parts.append('')
        header_parts.append(device_funcs)

    header = '\n'.join(header_parts)

    # Build body preamble: local variable declarations that reference
    # thread_position_in_grid / threads_per_threadgroup.
    # MLX auto-injects these as kernel parameters when they appear in source.
    preamble_lines = []

    if uses_2d:
        # 2D: compute pid/lid per axis from injected thread variables
        preamble_lines.append('    // MLX thread variable mapping')
        preamble_lines.append('    uint __pid_x = thread_position_in_grid.x / threads_per_threadgroup.x;')
        preamble_lines.append('    uint __pid_y = thread_position_in_grid.y / threads_per_threadgroup.y;')
        preamble_lines.append('    uint __pid_z = thread_position_in_grid.z / threads_per_threadgroup.z;')
        preamble_lines.append('    uint __lid_x = thread_position_in_grid.x % threads_per_threadgroup.x;')
        preamble_lines.append('    uint __lid_y = thread_position_in_grid.y % threads_per_threadgroup.y;')
        preamble_lines.append('    uint __lid_z = thread_position_in_grid.z % threads_per_threadgroup.z;')
        preamble_lines.append('    uint __tid_x = thread_position_in_grid.x;')

        # Replace the body's decomposition lines with our computed values
        raw_body = re.sub(r'uint\s+pid\s*=\s*pid3\.x\s*;', 'uint pid = __pid_x;', raw_body)
        raw_body = re.sub(r'uint\s+lid\s*=\s*lid3\.x\s*;', 'uint lid = __lid_x;', raw_body)
        raw_body = re.sub(r'uint\s+tid\s*=\s*tid3\.x\s*;', 'uint tid = __tid_x;', raw_body)
        raw_body = re.sub(r'uint\s+pid_y\s*=\s*pid3\.y\s*;', 'uint pid_y = __pid_y;', raw_body)
        raw_body = re.sub(r'uint\s+pid_z\s*=\s*pid3\.z\s*;', 'uint pid_z = __pid_z;', raw_body)
    else:
        # 1D: pid/lid/tid were kernel params in original MSL — declare as locals
        preamble_lines.append('    // MLX thread variable mapping')
        preamble_lines.append('    uint pid = thread_position_in_grid.x / threads_per_threadgroup.x;')
        preamble_lines.append('    uint lid = thread_position_in_grid.x % threads_per_threadgroup.x;')
        preamble_lines.append('    uint tid = thread_position_in_grid.x;')

    if uses_simd:
        # MLX injects simdgroup_index_in_threadgroup when referenced in source
        preamble_lines.append('    uint sgitg = simdgroup_index_in_threadgroup;')
        preamble_lines.append('    uint tiisg = thread_index_in_simdgroup;')

    if uses_tpg:
        # tpg (threadgroups_per_grid) isn't auto-injected by MLX.
        # Metal's [[threadgroups_per_grid]] attribute is not available through
        # MLX's metal_kernel API, so we pass the grid dimensions as scalar
        # arguments injected by the launcher at dispatch time.
        if 0 in tpg_axes:
            preamble_lines.append('    uint tpg = __tpg_dim0;')
        if 1 in tpg_axes:
            preamble_lines.append('    uint tpg_y = __tpg_dim1;')
        if 2 in tpg_axes:
            preamble_lines.append('    uint tpg_z = __tpg_dim2;')

        # Strip the original tpg decomposition lines from the body
        # (emitted by msl_emitter for the 2D case: uint tpg = tpg3.x; etc.)
        raw_body = re.sub(r'\s*uint\s+tpg\s*=\s*tpg3\.x\s*;\n?', '\n', raw_body)
        raw_body = re.sub(r'\s*uint\s+tpg_y\s*=\s*tpg3\.y\s*;\n?', '\n', raw_body)
        raw_body = re.sub(r'\s*uint\s+tpg_z\s*=\s*tpg3\.z\s*;\n?', '\n', raw_body)

    body = '\n'.join(preamble_lines) + '\n' + raw_body

    return MSLExtraction(
        kernel_name=kernel_name,
        body=body,
        header=header,
        input_names=input_names,
        output_names=output_names,
        scalar_names=scalar_names,
        scalar_types=scalar_types,
        output_ptr_indices=output_ptr_idx_set,
        uses_simd=uses_simd,
        uses_2d=uses_2d,
        uses_tpg=uses_tpg,
        tpg_axes=tpg_axes if tpg_axes else None,
    )


def _parse_signature(sig_text: str):
    """Parse kernel signature to extract buffer args and thread variables.

    Returns:
        (ptr_args, scalar_args, thread_vars)
    """
    ptr_args = []
    scalar_args = []
    thread_vars = set()

    for m in re.finditer(
        r'(?:volatile\s+)?device\s+(?:const\s+)?(\w+)\*\s+(\w+)\s+\[\[buffer\(\d+\)\]\]',
        sig_text,
    ):
        dtype, name = m.group(1), m.group(2)
        ptr_args.append((name, dtype))

    for m in re.finditer(
        r'constant\s+(\w+)&\s+(\w+)\s+\[\[buffer\(\d+\)\]\]',
        sig_text,
    ):
        dtype, name = m.group(1), m.group(2)
        scalar_args.append((name, dtype))

    for m in re.finditer(r'uint3?\s+(\w+)\s+\[\[', sig_text):
        thread_vars.add(m.group(1))

    return ptr_args, scalar_args, thread_vars


def _extract_device_functions(pre_kernel: str) -> str:
    """Extract device functions from code before the kernel."""
    lines = pre_kernel.split('\n')
    func_lines = []
    in_func = False

    for line in lines:
        stripped = line.strip()
        if stripped.startswith('#include') or stripped.startswith('using '):
            continue
        if not stripped:
            if in_func:
                func_lines.append(line)
            continue
        if ('void ' in stripped or 'float ' in stripped or 'int ' in stripped) and \
           not stripped.startswith('kernel '):
            in_func = True
        if in_func:
            func_lines.append(line)

    return '\n'.join(func_lines).strip()
